---

- name: Prepare Automation Controller
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Ensure required connection variables are defined
      ansible.builtin.assert:
        that:
          - lookup('env', 'CONTROLLER_HOST') is defined
          - lookup('env', 'CONTROLLER_HOST') | length > 0
          - lookup('env', 'CONTROLLER_USERNAME') is defined
          - lookup('env', 'CONTROLLER_USERNAME') | length > 0
          - lookup('env', 'CONTROLLER_PASSWORD') is defined
          - lookup('env', 'CONTROLLER_PASSWORD') | length > 0
        quiet: true
        fail_msg: ""
  tasks:
    - name: Get job list
      awx.awx.job_list:
        status: failed
