# code: language=yaml
site_name: Computacenter QeP
site_description: Small demo project for automating stuff during QeP
copyright: Copyright &copy; Computacenter 2024
edit_uri: ""
extra:
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/timgrt/qep-ee/general
      name: Execution Environment Container im Docker Hub
extra_css:
  - assets/stylesheets/tables.css
extra_javascript:
  - assets/javascripts/extra/refresh-on-toggle-dark-light.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path:
        - .
        - docs/ansible/snippets
        - docs/automation-platform/snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      title: On this page
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: en
      separator: '[\s]'
  - git-revision-date-localized:
    # This plugin needs a Git executable and the .git folder
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
      fallback_to_build_date: true
      locale: en
  - privacy
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: octicons/terminal-24
  logo: assets/images/computacenter-logo-white.png
  language: de
  favicon: assets/images/computacenter-logo.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.section
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/TimGrt/automation-demo
repo_name: TimGrt/automation-demo
watch:
  - variables.yml
# Navigation definition
nav:
  - index.md
  - "Teil 1:<br>Infrastructure as Code": part1.md
  - "Teil 2:<br>Code-Update": part2.md
