---

- name: Prepare Automation Controller
  hosts: localhost
  connection: local
  vars_files:
    - variables.yml
  pre_tasks:
    - name: Ensure required connection variables are defined
      ansible.builtin.assert:
        that:
          - lookup('env', 'CONTROLLER_HOST') is defined
          - lookup('env', 'CONTROLLER_HOST') | length > 0
          - lookup('env', 'CONTROLLER_USERNAME') is defined
          - lookup('env', 'CONTROLLER_USERNAME') | length > 0
          - lookup('env', 'CONTROLLER_PASSWORD') is defined
          - lookup('env', 'CONTROLLER_PASSWORD') | length > 0
        quiet: true
        fail_msg: "Variables for accessing Automation controller are missing! Export the variables."
  tasks:
    - name: Add project with content for QEP
      awx.awx.project:
        name: QEP Repository
        organization: Default
        scm_type: git
        scm_url: https://github.com/TimGrt/qep.git
        scm_branch: dev
        scm_update_on_launch: true

    - name: Ensure all hosts from web group are enabled
      awx.awx.host:
        name: "{{ item }}"
        inventory: Workshop Inventory
        enabled: true
      loop:
        - node1
        - node2
        - node3

    - name: Add Job Template for Webserver Deployment with Survey
      awx.awx.job_template:
        name: Webserver Deployment
        description: Personalisierter Webserver für das QEP
        inventory: Workshop Inventory
        project: QEP Repository
        playbook: playbook_webserver_deployment.yml
        credentials:
          - Workshop Credential
        survey_enabled: true
        survey_spec:
          name: Webserver Deployment Survey
          description: Survey Spezifikation für Webserver Deployment Template
          spec:
            - question_name: Für wen soll der Webserver personalisiert werden?
              required: true
              type: multiplechoice
              choices: "{{ attendee_list }}"
              variable: webserver_owner
              default: ""
